
import 'package:grocery_app/models/products.dart';

class MyProducts{
  static List<Product> allProducts=[
    Product(id: 1, name: "Iphone 15", category: "Popular", price: 100000.00, description: "Latest iPhone model", image: "https://www.apple.com/newsroom/images/2023/09/apple-debuts-iphone-15-and-iphone-15-plus/article/Apple-iPhone-15-lineup-hero-230912_inline.jpg.large.jpg", quantity: 1),
  Product(id: 2, name: "Samsung S24 Ultra", category: "Out of stock", price: 110000.00, description: "High-end Samsung phone", image: "https://imgs.search.brave.com/BCK_Akf-kvXR1mDOB1y6wD-_8jkeG3og2BLC0dzIRhs/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly93d3cu/OTEtaW1nLmNvbS9n/YWxsZXJ5X2ltYWdl/c191cGxvYWRzLzQv/ZS80ZTU3Yjg1NDE1/ZjdhNGZmYzI0YTUz/NWMzMDI0NDYxMmVi/YTBiZTAwLmpwZz90/cj1oLTU1MCx3LTAs/Yy1hdF9tYXg", quantity: 1),
  Product(id: 3, name: "One Plus 12", category: "Trending", price: 65000.00, description: "Latest One Plus phone", image: "https://oasis.opstatics.com/content/dam/oasis/page/2023/cn/12/12-black.png", quantity: 1),
  Product(id: 4, name: "Sony WH-1000XM5", category: "Popular", price: 30000.00, description: "Noise-canceling headphones", image: "https://imgs.search.brave.com/S0aUzd8NJfQwGEMRndCNsyXO5WHw0JsevI56wZ6lw-o/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL0kv/NTF3ZGF2MForMkwu/anBn", quantity: 1),
  Product(id: 5, name: "Dell XPS 15", category: "Trending", price: 150000.00, description: "High-performance laptop", image: "https://imgs.search.brave.com/mxLwFQndp-GnEiDVjPviQ8M-V1fo25B8P6fxQLiLcoY/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93d3cu/Y25ldC5jb20vYS9p/bWcvcmVzaXplLzk4/OTA0ZWNhYzczZDA0/MWZlYWVlNzFiZWZk/YWU5YmE5YTEyZWQ0/YTUvaHViLzIwMjMv/MDUvMDQvMzNjNTg0/Y2YtM2RhYi00MTYy/LWJlYjUtNjUzNDc5/ZGQ1YWQ0L2RlbGwt/eHBzLTE1LTIwMjMt/MS5qcGc_YXV0bz13/ZWJwJndpZHRoPTEy/MDA", quantity: 1),
  Product(id: 6, name: "Apple Watch Series 9", category: "Popular", price: 45000.00, description: "Smartwatch with advanced features", image: "https://imgs.search.brave.com/0evp9T3bwUawMYyZpg9pHL-au5IzQmivl3LfU0OMAO8/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9zczcu/dnp3LmNvbS9pcy9p/bWFnZS9WZXJpem9u/V2lyZWxlc3MvYXBw/bGUtd2F0Y2gtc2Vy/aWVzLTktZ3BzLWNl/bGx1bGFyLTQ1bW0t/bWlkbmlnaHQtYWx1/bWludW0tY2FzZS1t/aWRuaWdodC1zcG9y/dC1iYW5kLW1ybWQz/bGwtYS1hP2hlaT0y/NTAmYmdjPWY2ZjZm/Ng.jpeg", quantity: 1),
  Product(id: 7, name: "GoPro HERO12", category: "Trending", price: 55000.00, description: "Action camera for adventure enthusiasts", image: "https://imgs.search.brave.com/jUB7-M4qBIIAQ3czLNNoNpXlWYvwjCmK0Xkpp9Puadk/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL0kv/NzFwNVY4K09uZkwu/anBn", quantity: 1),
  Product(id: 8, name: "Samsung Galaxy Tab S9", category: "Popular", price: 75000.00, description: "High-resolution tablet", image: "https://imgs.search.brave.com/x4517esBDwtLYnHTtHcX8gwB_dtrSp5O6GCLkusOnxo/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9zczcu/dnp3LmNvbS9pcy9p/bWFnZS9WZXJpem9u/V2lyZWxlc3Mvc2Ft/c3VuZy1nYWxheHkt/dGFiLXM5LXBsdXMt/cHJlLW9yZGVyLTIw/MjM_aGVpPTI1MCZi/Z2M9ZjZmNmY2.jpeg", quantity: 1),
  Product(id: 9, name: "Google Pixel 8", category: "Trending", price: 90000.00, description: "Flagship smartphone by Google", image: "https://imgs.search.brave.com/d-ixIyXKxSGuM4CbiEeaUvu8uSvkCqG9G2uhxpoU7P4/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly90LW1v/YmlsZS5zY2VuZTcu/Y29tL2lzL2ltYWdl/L1RtdXNwcm9kL0dv/b2dsZS1QaXhlbC04/LU9ic2lkaWFuLWZy/b250aW1hZ2U.jpeg", quantity: 1),
  Product(id: 10, name: "Microsoft Surface Laptop 5", category: "Popular", price: 130000.00, description: "Stylish and powerful laptop", image: "https://imgs.search.brave.com/dXDpjOjnVMrxT8neq7gNQhyZDYCKTmrQe_OlT2AwGnI/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS53aXJlZC5jb20v/cGhvdG9zLzVkYWY1/ZTViZTIzMThjMDAw/OGZlMWNlNy9tYXN0/ZXIvd18xNjAwLGNf/bGltaXQvR2Vhci1T/dXJmYWNlUHJvNy01/LmpwZw", quantity: 1),
  Product(id: 11, name: "Amazon Echo Show 8", category: "Trending", price: 12000.00, description: "Smart display with Alexa", image: "https://imgs.search.brave.com/YRZ-CB4Ds2IpfHEPxcMT65KOk23JtOiSxEmCkyeeA-w/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL0kv/NzFKU005aTFiUUwu/anBn", quantity: 1),
  Product(id: 12, name: "Apple AirPods Pro 2", category: "Popular", price: 25000.00, description: "Wireless earbuds with noise cancellation", image: "https://imgs.search.brave.com/K_cLhDf6nvqR-sH9n_nF8veK8U6lX72J69Fq6pEattQ/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL0kv/MzFSTHVVSE42UEwu/anBn", quantity: 1),
  Product(id: 13, name: "HP Envy 14", category: "Trending", price: 140000.00, description: "Powerful and sleek laptop", image: "https://imgs.search.brave.com/7VoinvKR3rh-YdFx73Bztq9GIlHSdEnUnJ1MNaqe62c/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL0kv/NDFnR2hvUVNNZEwu/anBn", quantity: 1),
  Product(id: 14, name: "Oculus Quest 3", category: "Popular", price: 70000.00, description: "VR headset for immersive experiences", image: "https://imgs.search.brave.com/XFQRna1SnEW5lO83eMZW619ApnAZfgqRGRh3WDm6xSw/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL0kv/MzFnRVFoQUppcUwu/anBn", quantity: 1),
  Product(id: 15, name: "Bose QuietComfort 45", category: "Trending", price: 35000.00, description: "High-quality noise-canceling headphones", image: "https://imgs.search.brave.com/kR8q3708GIQC-8wnLl_cbcDlrHQN3zyDTzENRn-F9jE/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL0kv/NDFUeDkzTVVIQ0wu/anBn", quantity: 1),
  Product(id: 16, name: "Asus ROG Zephyrus G14", category: "Popular", price: 120000.00, description: "Gaming laptop with powerful specs", image: "https://imgs.search.brave.com/qsfpcUAsx8ylfTwAKH0L2yQyWoAPfmaDtKP-wtVqbEk/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9tdWx0/aW1lZGlhLmJieWNh/c3RhdGljLmNhL211/bHRpbWVkaWEvcHJv/ZHVjdHMvNTAweDUw/MC8xNjYvMTY2OTAv/MTY2OTA5OTEuanBn", quantity: 1),
  Product(id: 17, name: "Fitbit Charge 6", category: "Trending", price: 20000.00, description: "Fitness tracker with health monitoring", image: "https://imgs.search.brave.com/45oG7d87xPFVSGeiAbaEeg1NlxhC0jDyZb24YuACNq8/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL0kv/NjF3bjJqZmhCa0wu/anBn", quantity: 1),
  Product(id: 18, name: "Canon EOS R8", category: "Popular", price: 140000.00, description: "Mirrorless camera with high resolution", image: "https://imgs.search.brave.com/bY4Tl-UkZl8Zf9dm0NppFV4jP0auXXauOfBpCL-lM4o/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL0kv/NDFMRmN2VmtLY0wu/anBn", quantity: 1),
  Product(id: 19, name: "LG UltraWide Monitor", category: "Trending", price: 40000.00, description: "Wide screen monitor for productivity", image: "https://imgs.search.brave.com/Z4_XMsmxry8s2Axf_u-ly4MLAwFFRN4WPJsI_Q4L2Tw/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9jMS5u/ZXdlZ2dpbWFnZXMu/Y29tL3Byb2R1Y3Rp/bWFnZS9uYjMwMC9B/NlpQRDIyMDgxMjA4/MFBISjg5LmpwZw", quantity: 1),
  Product(id: 20, name: "Jabra Elite 85t", category: "Popular", price: 28000.00, description: "True wireless earbuds with active noise cancellation", image: "https://imgs.search.brave.com/qQH3mr1zXRzqtxAAADDNtQLlE3pB6BD1-4jdx7SOzq0/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL0kv/NzEtM0MzYVl2ZUwu/anBn", quantity: 1),
  Product(
    id: 1,
    name: 'All-Purpose Cleaner',
    category: 'Cleaners',
    price: 200.00,
    description: 'Versatile cleaner suitable for multiple surfaces.',
    image: 'https://imgs.search.brave.com/kJXAvsLViYV74dsp02pldqtuPzRblx9mGlPYsvpaNvI/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9oaXBz/LmhlYXJzdGFwcHMu/Y29tL3ZhZGVyLXBy/b2QuczMuYW1hem9u/YXdzLmNvbS8xNjU1/NTAzMDc4LTUxOTJ5/MzZ2WHlMLl9TTDUw/MF8uanBnP2Nyb3A9/MXh3OjEuMDB4aDtj/ZW50ZXIsdG9wJnJl/c2l6ZT05ODA6Kg',
    quantity: 1,
  ),
  Product(
    id: 2,
    name: 'Glass Cleaner',
    category: 'Cleaners',
    price: 150.0,
    description: 'Leaves glass surfaces streak-free and sparkling.',
    image: 'https://imgs.search.brave.com/H95ewogiWcJxnUXm60NrCTwCfd84YYSmaQew1jyuGNU/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly93d3cu/cHJvd2F4LmNvbS9j/ZG4vc2hvcC9wcm9k/dWN0cy9BR0MtMTgt/QWVyb3NvbC1HbGFz/cy1DbGVhbmVyXzUz/M3guanBnP3Y9MTY0/OTgyODk5OQ',
    quantity: 1,
  ),
  Product(
    id: 3,
    name: 'Disinfectant Spray',
    category: 'Cleaners',
    price: 100.0,
    description: 'Kills germs and bacteria on various surfaces.',
    image: 'https://imgs.search.brave.com/oGNp2ZvTNs3l7g830Pj7pQfiTL-Cf3WX71W_HG3tXyk/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS1jbGRucnkucy1u/YmNuZXdzLmNvbS9p/bWFnZS91cGxvYWQv/dF9maXQtMzIwdyxm/X2F1dG8scV9hdXRv/OmJlc3QvbmV3c2Nt/cy8yMDIzXzE3LzM1/NzM5MzYvZ3Vlc3Qt/ZTVlMzM0YmMtNGU0/NS00OGFlLWI1Yjgt/ZjM3MjczYzQxODUy/LTYzM2MzYTQ2OGEy/MDIuanBn',
    quantity: 1,
  ),
  Product(
    id: 4,
    name: 'Floor Cleaner',
    category: 'Cleaners',
    price: 200.0,
    description: 'Specially formulated for cleaning all types of flooring.',
    image: 'https://imgs.search.brave.com/NdDlQ3YM1cOdMbKfGOppOSwTxX2Aet4maLN17LX-DrQ/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly93d3cu/ZmFtaWx5aGFuZHlt/YW4uY29tL3dwLWNv/bnRlbnQvdXBsb2Fk/cy8yMDIxLzA0LzUx/SHFZbDFySFNMLl9B/Q19TWDY3OV8uanBn/P2ZpdD02OTYsNjk2',
    quantity: 1,
  ),
  Product(
    id: 5,
    name: 'Bathroom Cleaner',
    category: 'Cleaners',
    price: 180.0,
    description: 'Removes tough stains and grime from bathroom surfaces.',
    image: 'https://imgs.search.brave.com/49q8PEN4zTqc6YEPYmpADCSi3bZ7TVFVmtxk70oA7dM/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL0kv/NzFyZzFZTjg4cUwu/anBn',
    quantity: 1,
  ),
  Product(
    id: 6,
    name: 'Kitchen Degreaser',
    category: 'Cleaners',
    price: 220.0,
    description: 'Cuts through grease and grime in the kitchen.',
    image: 'https://imgs.search.brave.com/tgI5EAALDqTf03zEMRjmDZ22UyvHqJc3CKxnjndrFJI/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL0kv/NTFEbzBRUXFKUEwu/anBn',
    quantity: 1,
  ),
  
  Product(
    id: 7,
    name: 'Carpet Cleaner',
    category: 'Cleaners',
    price: 9000.0,
    description: 'Deep cleans and refreshes carpets.',
    image: 'https://imgs.search.brave.com/WuVZLSRN1tpbMqlWoB3EsU2-_4DC5VWPzZ3wDMUdIiE/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5nZXR0eWltYWdl/cy5jb20vaWQvMTgy/NzM4NTMzL3Bob3Rv/L2NhcnBldC1jbGVh/bmVyLXJlc2lkZW50/aWFsLmpwZz9zPTYx/Mng2MTImdz0wJms9/MjAmYz1BRHptY1pp/aFI3LWJnZV82Uk12/RG1vbEJmSlZGdWRX/djI5RWptQzhxUEJN/PQ',
    quantity: 1,
  ),
  Product(
    id: 9,
    name: 'Wood Polish',
    category: 'Cleaners',
    price: 170.0,
    description: 'Enhances the shine and protects wooden surfaces.',
    image: 'https://imgs.search.brave.com/XIqDDOzaoxmSLy2VpEqmjMs12zmRNE7e3ib9pJtMHKQ/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL0kv/NzFOQmZIUytvcFMu/anBn',
    quantity: 1,
  ),
  Product(
    id: 12,
    name: 'Leather Cleaner',
    category: 'Cleaners',
    price: 240.0,
    description: 'Specially designed for cleaning and conditioning leather.',
    image: 'https://imgs.search.brave.com/ZjMDowlez9M8qAcVf-PznHp_ubGBJuI1G2pVoSFpJQM/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93d3cu/bGVhdGhlcmhvbmV5/LmNvbS9jZG4vc2hv/cC9maWxlcy9NYWlu/OG96XzE2MDB4Lmpw/Zz92PTE3MTUxMzE1/MjQ',
    quantity: 1,
  ),
  Product(
    id: 13,
    name: 'Toilet Bowl Cleaner',
    category: 'Cleaners',
    price: 120.0,
    description: 'Cleans and disinfects toilet bowls with ease.',
    image: 'https://imgs.search.brave.com/x951gckqB8BLLt1TqFcoIKSBHZjDNUQoLNEkY3prSbw/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9sZW1p/c2hpbmUuY29tL2Nk/bi9zaG9wL2ZpbGVz/L1RvaWxldC1Cb3ds/LUNsZWFuZXItMjQt/T3ouanBnP3Y9MTcw/NTY3NjE0OCZ3aWR0/aD0xMDAw',
    quantity: 1,
  ),

    Product(
    id: 1,
    name: 'Carrot',
    category: 'Vegetables',
    price: 30.0, 
    description: 'Fresh and crunchy carrots rich in vitamins.',
    image: 'https://imgs.search.brave.com/3F1BZWwjx9473_ALub2SWqea5wfg6OThyaW6zqw5JyA/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5nZXR0eWltYWdl/cy5jb20vaWQvOTA5/MjE2NzI2L3Bob3Rv/L2NhcnJvdC5qcGc_/cz02MTJ4NjEyJnc9/MCZrPTIwJmM9RUFi/ZTJLR0JIOU9Sd0JU/dE9Faml3d2hVRk80/MU1RMmxKbVRnLXlJ/azZndz0',
    quantity: 1,
  ),
  Product(
    id: 2,
    name: 'Broccoli',
    category: 'Vegetables',
    price: 40.0,
    description: 'Green and nutritious broccoli with a high vitamin C content.',
    image: 'https://imgs.search.brave.com/l-T_UZ55GzMEmlKNLB2ES2R3sPxY7dAipKfO-Mkr3fc/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5pc3RvY2twaG90/by5jb20vaWQvMTQ3/MDYwNjIxL3Bob3Rv/L2Jyb2Njb2xpLmpw/Zz9zPTYxMng2MTIm/dz0wJms9MjAmYz1J/MWNDeEx4Y2kyM25y/U05aYjdvNmdzcVVZ/QjkxMXo2SVpsTGRF/T2s0STlNPQ',
    quantity: 1,
  ),
  Product(
    id: 3,
    name: 'Tomato',
    category: 'Vegetables',
    price: 25.0,
    description: 'Juicy tomatoes perfect for salads and cooking.',
    image: 'https://imgs.search.brave.com/l1uhgFLvv-ygZtfCMKqkXf0JA7kCgvKwKV2D2lYwjiU/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly91cGxv/YWQud2lraW1lZGlh/Lm9yZy93aWtpcGVk/aWEvY29tbW9ucy90/aHVtYi84Lzg5L1Rv/bWF0b19qZS5qcGcv/NTEycHgtVG9tYXRv/X2plLmpwZw',
    quantity: 1,
  ),
  Product(
    id: 4,
    name: 'Spinach',
    category: 'Vegetables',
    price: 50.0,
    description: 'Fresh spinach leaves rich in iron and vitamins.',
    image: 'https://imgs.search.brave.com/py1df258pGzMhhgtRKczhDHeui7Ha0HuuQ3aY0NyBGk/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5nZXR0eWltYWdl/cy5jb20vaWQvMTY5/OTgzNzkxL3Bob3Rv/L3NwaW5hY2guanBn/P3M9NjEyeDYxMiZ3/PTAmaz0yMCZjPTFM/OXFKTDNCVFl1ck85/N0h5RXhmRVNrS3lG/UkV6UjM1RVJlSEhs/aDlpYms9',
    quantity: 1,
  ),
  Product(
    id: 5,
    name: 'Cucumber',
    category: 'Vegetables',
    price: 20.0,
    description: 'Crisp and refreshing cucumbers, great for salads.',
    image: 'https://imgs.search.brave.com/CCwd3ggQUAIXxSgyRYhbhDEcvg8TyUOuXljMcMgYkZ4/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5pc3RvY2twaG90/by5jb20vaWQvMTUz/NTU2MzM2L3Bob3Rv/L2N1Y3VtYmVyLXNs/aWNlLmpwZz9zPTYx/Mng2MTImdz0wJms9/MjAmYz1NV294cmM0/bk9uU2FkU1hRclZD/TEd5N29SNmt2eWVO/TDFOamI1bGg4Zl9J/PQ',
    quantity: 1,
  ),
  Product(
    id: 6,
    name: 'Bell Pepper',
    category: 'Vegetables',
    price: 35.0,
    description: 'Sweet and crunchy bell peppers in various colors.',
    image: 'https://imgs.search.brave.com/-SiHQIvnrV4Rxkt2Ix679CdCwBceMImwovOhyCBIw9k/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5nZXR0eWltYWdl/cy5jb20vaWQvMTcx/MjgxMzY0L3Bob3Rv/L2JlbGwtcGVwcGVy/cy5qcGc_cz02MTJ4/NjEyJnc9MCZrPTIw/JmM9UHBycDBjQzh3/ODZ2VHRUXzhDS1pv/bHliU25HLWcxOGFY/S2U4OHUyVi01dz0',
    quantity: 1,
  ),
  Product(
    id: 7,
    name: 'Potato',
    category: 'Vegetables',
    price: 25.0,
    description: 'Versatile and hearty potatoes for various dishes.',
    image: 'https://imgs.search.brave.com/PSjRGSd8lGymy8L-NE0eLb8iDEfvgpidKeIxsOUpbBo/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly90My5m/dGNkbi5uZXQvanBn/LzAwLzg1Lzc5Lzky/LzM2MF9GXzg1Nzk5/Mjc4XzBCQkdWOU9B/ZFFEVExuS3dBUEJD/Y2cxSjdRdGlpZUpZ/LmpwZw',
    quantity: 1,
  ),
  Product(
    id: 8,
    name: 'Onion',
    category: 'Vegetables',
    price: 30.0,
    description: 'Essential cooking ingredient with a strong flavor.',
    image: 'https://imgs.search.brave.com/RB8DTE3u7C1EghTdDA_LH_qDv8t5o-z_wnh3miLvFSo/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9pbWcu/ZnJlZXBpay5jb20v/ZnJlZS1waG90by9y/ZWQtb25pb25fMTQ0/NjI3LTE1NDE2Lmpw/Zz9zaXplPTYyNiZl/eHQ9anBn',
    quantity: 1,
  ),
  Product(
    id: 9,
    name: 'Garlic',
    category: 'Vegetables',
    price: 40.0,
    description: 'Aromatic garlic cloves perfect for flavoring dishes.',
    image: 'https://imgs.search.brave.com/Lw3PZUWZO9HQXZs6mt5Q9YcgA1ueW4_XvtsbjYzaEOU/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5pc3RvY2twaG90/by5jb20vaWQvNDk5/MTQ3ODY0L3Bob3Rv/L2dhcmxpYy5qcGc_/cz02MTJ4NjEyJnc9/MCZrPTIwJmM9LTli/NDgzVjZVUDJVcmxq/RVlaRGNFQkV3emtQ/cWIzdTVNSUozLU1h/b2Z1Yz0',
    quantity: 1,
  ),
  Product(
    id: 10,
    name: 'Sweet Potato',
    category: 'Vegetables',
    price: 45.0,
    description: 'Nutritious and sweet, ideal for roasting or baking.',
    image: 'https://imgs.search.brave.com/p7U6DqKhDg_yV-8en-cVtfow1drcrr8Hm6CNEYexxEI/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly90My5m/dGNkbi5uZXQvanBn/LzAyLzI0LzkxLzk0/LzM2MF9GXzIyNDkx/OTQ1OV9HMDhLWENY/NVo2N0N2RlhUd1J4/ell6azl2WVZ5Qkcx/SS5qcGc',
    quantity: 1,
  ),
  Product(
    id: 11,
    name: 'Cauliflower',
    category: 'Vegetables',
    price: 55.0,
    description: 'Versatile cauliflower, great for steaming or stir-frying.',
    image: 'https://imgs.search.brave.com/PTtTKQnJ7bAJISEdd2_zWA6keeR3OzpZOF1b2-lEp-4/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5nZXR0eWltYWdl/cy5jb20vaWQvODU2/MzY5MjEvcGhvdG8v/Y2F1bGlmbG93ZXIu/anBnP3M9NjEyeDYx/MiZ3PTAmaz0yMCZj/PW5YUG5RUXdFWFdK/c25vZnZ0MG9TeWh6/aldMOHpNbzBldFV6/M281dlo3cFU9',
    quantity: 1,
  ),
  Product(
    id: 12,
    name: 'Green Beans',
    category: 'Vegetables',
    price: 35.0,
    description: 'Crisp and fresh green beans, perfect for a side dish.',
    image: 'https://imgs.search.brave.com/O5LIftgwZS7wRf9qX6uKKz83Yrvfdq1Uih9phK6Ew4I/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly93d3cu/dHdvcGVhc2FuZHRo/ZWlycG9kLmNvbS93/cC1jb250ZW50L3Vw/bG9hZHMvMjAxOS8w/OC9Ud29QZWFzX1NM/Q18yNTA4LTY1MHg5/NzUuanBn',
    quantity: 1,
  ),
  Product(
    id: 13,
    name: 'Zucchini',
    category: 'Vegetables',
    price: 30.0,
    description: 'Tender zucchinis ideal for grilling or sautéing.',
    image: 'https://imgs.search.brave.com/GhyJ4ZR5Q_MgYAHqeOZn3-sYheyTvrVbFGswUpn_hwo/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly90NC5m/dGNkbi5uZXQvanBn/LzAwLzY5Lzg4LzY3/LzM2MF9GXzY5ODg2/NzEzX2d1RWFMaE1T/aVM5N1VDUnlBQjN5/S2ZqYVY4VDMxQVRZ/LmpwZw',
    quantity: 1,
  ),
  Product(
    id: 14,
    name: 'Eggplant',
    category: 'Vegetables',
    price: 50.0,
    description: 'Rich and flavorful eggplants for a variety of dishes.',
    image: 'https://imgs.search.brave.com/EnqZkY5NS4m80Z0eROlVuAFLZvRJyWzI1uEwkBK_ko8/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly90My5m/dGNkbi5uZXQvanBn/LzAwLzc4LzM3Lzc0/LzM2MF9GXzc4Mzc3/NDU5X1laMmd4ZTQ2/UEptZ3RwWGplSEM1/bDZxUU9MdElmcGUz/LmpwZw',
    quantity: 1,
  ),
  Product(
    id: 15,
    name: 'Beetroot',
    category: 'Vegetables',
    price: 40.0,
    description: 'Sweet and earthy beetroot for salads and juices.',
    image: 'https://imgs.search.brave.com/QG4Ok3EJ8btGjADi3AgNNzQG1fsJX6e-T3gL8lP0Ry4/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5pc3RvY2twaG90/by5jb20vaWQvMTYy/NjgyOTYxL3Bob3Rv/L2JlZXRyb290Lmpw/Zz9zPTYxMng2MTIm/dz0wJms9MjAmYz1B/ekhtSjZmUGE0NEJO/N3lfcmppOW56aUlY/TXVPclBlVTUwMktw/c1B2NktzPQ',
    quantity: 1,
  ),
  Product(
    id: 16,
    name: 'Sweet Corn',
    category: 'Vegetables',
    price: 30.0,
    description: 'Sweet and juicy corn on the cob, great for grilling.',
    image: 'https://imgs.search.brave.com/HuQHwNh3Urz5nAuNNeMauHl__bsHQHtV673m1pgf_Z4/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5nZXR0eWltYWdl/cy5jb20vaWQvMTUz/NDgyNTcyL3Bob3Rv/L3N3ZWV0LWNvcm4u/anBnP3M9NjEyeDYx/MiZ3PTAmaz0yMCZj/PUlvd09fNHA4VG5w/eXVITUhPTG1QWnNn/d3lLMVdzenAyd3kx/aDVvSWZ6bG89',
    quantity: 1,
  ),
  Product(
    id: 17,
    name: 'Radish',
    category: 'Vegetables',
    price: 25.0,
    description: 'Crunchy radishes with a spicy kick.',
    image: 'https://imgs.search.brave.com/Bnj33ej_qtTz9Sn8zB1Ox-QlLdYhz0z8f_Gk4iiUVBM/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5nZXR0eWltYWdl/cy5jb20vaWQvMTQz/NDUwNTA4L3Bob3Rv/L3doaXRlLXJhZGlz/aC5qcGc_cz02MTJ4/NjEyJnc9MCZrPTIw/JmM9QW80Z2ItQm1h/WlZhT2lKVDdqR0lV/SEdOWFRhQVNncVZU/ZFByTjVUYm0xOD0',
    quantity: 1,
  ),
  Product(
    id: 18,
    name: 'Kale',
    category: 'Vegetables',
    price: 40.0,
    description: 'Nutrient-dense kale leaves, great for salads and smoothies.',
    image: 'https://imgs.search.brave.com/qz7Vm0fMgB3E4dvBN2CDo_1N7hiGUFeaAF4bSPvn_Ls/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9pMC53/cC5jb20vaW1hZ2Vz/LXByb2QuaGVhbHRo/bGluZS5jb20vaGxj/bXNyZXNvdXJjZS9p/bWFnZXMvQU5faW1h/Z2VzL2JlbmVmaXRz/LW9mLWthbGUtMTI5/Nng3MjgtZmVhdHVy/ZS5qcGc_dz0xMTU1/Jmg9MTUyOA',
    quantity: 1,
  ),
  Product(
    id: 19,
    name: 'Brussels Sprouts',
    category: 'Vegetables',
    price: 60.0,
    description: 'Nutritious Brussels sprouts, ideal for roasting.',
    image: 'https://imgs.search.brave.com/2AKtaZysWZZ7OxzpHKrxcZF4AFW88xDnUzFNxACvnFk/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5pc3RvY2twaG90/by5jb20vaWQvMTcw/MDY5NTk2L3Bob3Rv/L2JydXNzZWxzLXNw/cm91dHMuanBnP3M9/NjEyeDYxMiZ3PTAm/az0yMCZjPTlxMzkz/LThkSHlqaEh2V3Vy/Tlp5RWMzQ29xMDBq/cmhqQVUzRG1kcTZC/WUU9',
    quantity: 1,
  ),
  Product(
    id: 20,
    name: 'Pumpkin',
    category: 'Vegetables',
    price: 70.0,
    description: 'Sweet and versatile pumpkin, perfect for soups and pies.',
    image: 'https://imgs.search.brave.com/EWw9hYzw5sWJ5ClWerdqQ4YnG8Hb4hlgU5DUKm-zB6s/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly90My5m/dGNkbi5uZXQvanBn/LzA0Lzk2LzM2LzY0/LzM2MF9GXzQ5NjM2/NjQ1Ml8wVnZzdE45/ZXBxbGRIVHdYbUE3/WWFiRHJ3VUdid2lT/VC5qcGc',
    quantity: 1,
  ),
  ];

  static List<Product> electronics=[
  Product(id: 1, name: "Iphone 15", category: "Popular", price: 100000.00, description: "Latest iPhone model", image: "https://www.apple.com/newsroom/images/2023/09/apple-debuts-iphone-15-and-iphone-15-plus/article/Apple-iPhone-15-lineup-hero-230912_inline.jpg.large.jpg", quantity: 1),
  Product(id: 2, name: "Samsung S24 Ultra", category: "Out of stock", price: 110000.00, description: "High-end Samsung phone", image: "https://imgs.search.brave.com/BCK_Akf-kvXR1mDOB1y6wD-_8jkeG3og2BLC0dzIRhs/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly93d3cu/OTEtaW1nLmNvbS9n/YWxsZXJ5X2ltYWdl/c191cGxvYWRzLzQv/ZS80ZTU3Yjg1NDE1/ZjdhNGZmYzI0YTUz/NWMzMDI0NDYxMmVi/YTBiZTAwLmpwZz90/cj1oLTU1MCx3LTAs/Yy1hdF9tYXg", quantity: 1),
  Product(id: 3, name: "One Plus 12", category: "Trending", price: 65000.00, description: "Latest One Plus phone", image: "https://oasis.opstatics.com/content/dam/oasis/page/2023/cn/12/12-black.png", quantity: 1),
  Product(id: 4, name: "Sony WH-1000XM5", category: "Popular", price: 30000.00, description: "Noise-canceling headphones", image: "https://imgs.search.brave.com/S0aUzd8NJfQwGEMRndCNsyXO5WHw0JsevI56wZ6lw-o/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL0kv/NTF3ZGF2MForMkwu/anBn", quantity: 1),
  Product(id: 5, name: "Dell XPS 15", category: "Trending", price: 150000.00, description: "High-performance laptop", image: "https://imgs.search.brave.com/mxLwFQndp-GnEiDVjPviQ8M-V1fo25B8P6fxQLiLcoY/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93d3cu/Y25ldC5jb20vYS9p/bWcvcmVzaXplLzk4/OTA0ZWNhYzczZDA0/MWZlYWVlNzFiZWZk/YWU5YmE5YTEyZWQ0/YTUvaHViLzIwMjMv/MDUvMDQvMzNjNTg0/Y2YtM2RhYi00MTYy/LWJlYjUtNjUzNDc5/ZGQ1YWQ0L2RlbGwt/eHBzLTE1LTIwMjMt/MS5qcGc_YXV0bz13/ZWJwJndpZHRoPTEy/MDA", quantity: 1),
  Product(id: 6, name: "Apple Watch Series 9", category: "Popular", price: 45000.00, description: "Smartwatch with advanced features", image: "https://imgs.search.brave.com/0evp9T3bwUawMYyZpg9pHL-au5IzQmivl3LfU0OMAO8/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9zczcu/dnp3LmNvbS9pcy9p/bWFnZS9WZXJpem9u/V2lyZWxlc3MvYXBw/bGUtd2F0Y2gtc2Vy/aWVzLTktZ3BzLWNl/bGx1bGFyLTQ1bW0t/bWlkbmlnaHQtYWx1/bWludW0tY2FzZS1t/aWRuaWdodC1zcG9y/dC1iYW5kLW1ybWQz/bGwtYS1hP2hlaT0y/NTAmYmdjPWY2ZjZm/Ng.jpeg", quantity: 1),
  Product(id: 7, name: "GoPro HERO12", category: "Trending", price: 55000.00, description: "Action camera for adventure enthusiasts", image: "https://imgs.search.brave.com/jUB7-M4qBIIAQ3czLNNoNpXlWYvwjCmK0Xkpp9Puadk/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL0kv/NzFwNVY4K09uZkwu/anBn", quantity: 1),
  Product(id: 8, name: "Samsung Galaxy Tab S9", category: "Popular", price: 75000.00, description: "High-resolution tablet", image: "https://imgs.search.brave.com/x4517esBDwtLYnHTtHcX8gwB_dtrSp5O6GCLkusOnxo/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9zczcu/dnp3LmNvbS9pcy9p/bWFnZS9WZXJpem9u/V2lyZWxlc3Mvc2Ft/c3VuZy1nYWxheHkt/dGFiLXM5LXBsdXMt/cHJlLW9yZGVyLTIw/MjM_aGVpPTI1MCZi/Z2M9ZjZmNmY2.jpeg", quantity: 1),
  Product(id: 9, name: "Google Pixel 8", category: "Trending", price: 90000.00, description: "Flagship smartphone by Google", image: "https://imgs.search.brave.com/d-ixIyXKxSGuM4CbiEeaUvu8uSvkCqG9G2uhxpoU7P4/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly90LW1v/YmlsZS5zY2VuZTcu/Y29tL2lzL2ltYWdl/L1RtdXNwcm9kL0dv/b2dsZS1QaXhlbC04/LU9ic2lkaWFuLWZy/b250aW1hZ2U.jpeg", quantity: 1),
  Product(id: 10, name: "Microsoft Surface Laptop 5", category: "Popular", price: 130000.00, description: "Stylish and powerful laptop", image: "https://imgs.search.brave.com/dXDpjOjnVMrxT8neq7gNQhyZDYCKTmrQe_OlT2AwGnI/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS53aXJlZC5jb20v/cGhvdG9zLzVkYWY1/ZTViZTIzMThjMDAw/OGZlMWNlNy9tYXN0/ZXIvd18xNjAwLGNf/bGltaXQvR2Vhci1T/dXJmYWNlUHJvNy01/LmpwZw", quantity: 1),
  Product(id: 11, name: "Amazon Echo Show 8", category: "Trending", price: 12000.00, description: "Smart display with Alexa", image: "https://imgs.search.brave.com/YRZ-CB4Ds2IpfHEPxcMT65KOk23JtOiSxEmCkyeeA-w/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL0kv/NzFKU005aTFiUUwu/anBn", quantity: 1),
  Product(id: 12, name: "Apple AirPods Pro 2", category: "Popular", price: 25000.00, description: "Wireless earbuds with noise cancellation", image: "https://imgs.search.brave.com/K_cLhDf6nvqR-sH9n_nF8veK8U6lX72J69Fq6pEattQ/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL0kv/MzFSTHVVSE42UEwu/anBn", quantity: 1),
  Product(id: 13, name: "HP Envy 14", category: "Trending", price: 140000.00, description: "Powerful and sleek laptop", image: "https://imgs.search.brave.com/7VoinvKR3rh-YdFx73Bztq9GIlHSdEnUnJ1MNaqe62c/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL0kv/NDFnR2hvUVNNZEwu/anBn", quantity: 1),
  Product(id: 14, name: "Oculus Quest 3", category: "Popular", price: 70000.00, description: "VR headset for immersive experiences", image: "https://imgs.search.brave.com/XFQRna1SnEW5lO83eMZW619ApnAZfgqRGRh3WDm6xSw/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL0kv/MzFnRVFoQUppcUwu/anBn", quantity: 1),
  Product(id: 15, name: "Bose QuietComfort 45", category: "Trending", price: 35000.00, description: "High-quality noise-canceling headphones", image: "https://imgs.search.brave.com/kR8q3708GIQC-8wnLl_cbcDlrHQN3zyDTzENRn-F9jE/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL0kv/NDFUeDkzTVVIQ0wu/anBn", quantity: 1),
  Product(id: 16, name: "Asus ROG Zephyrus G14", category: "Popular", price: 120000.00, description: "Gaming laptop with powerful specs", image: "https://imgs.search.brave.com/qsfpcUAsx8ylfTwAKH0L2yQyWoAPfmaDtKP-wtVqbEk/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9tdWx0/aW1lZGlhLmJieWNh/c3RhdGljLmNhL211/bHRpbWVkaWEvcHJv/ZHVjdHMvNTAweDUw/MC8xNjYvMTY2OTAv/MTY2OTA5OTEuanBn", quantity: 1),
  Product(id: 17, name: "Fitbit Charge 6", category: "Trending", price: 20000.00, description: "Fitness tracker with health monitoring", image: "https://imgs.search.brave.com/45oG7d87xPFVSGeiAbaEeg1NlxhC0jDyZb24YuACNq8/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL0kv/NjF3bjJqZmhCa0wu/anBn", quantity: 1),
  Product(id: 18, name: "Canon EOS R8", category: "Popular", price: 140000.00, description: "Mirrorless camera with high resolution", image: "https://imgs.search.brave.com/bY4Tl-UkZl8Zf9dm0NppFV4jP0auXXauOfBpCL-lM4o/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL0kv/NDFMRmN2VmtLY0wu/anBn", quantity: 1),
  Product(id: 19, name: "LG UltraWide Monitor", category: "Trending", price: 40000.00, description: "Wide screen monitor for productivity", image: "https://imgs.search.brave.com/Z4_XMsmxry8s2Axf_u-ly4MLAwFFRN4WPJsI_Q4L2Tw/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9jMS5u/ZXdlZ2dpbWFnZXMu/Y29tL3Byb2R1Y3Rp/bWFnZS9uYjMwMC9B/NlpQRDIyMDgxMjA4/MFBISjg5LmpwZw", quantity: 1),
  Product(id: 20, name: "Jabra Elite 85t", category: "Popular", price: 28000.00, description: "True wireless earbuds with active noise cancellation", image: "https://imgs.search.brave.com/qQH3mr1zXRzqtxAAADDNtQLlE3pB6BD1-4jdx7SOzq0/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL0kv/NzEtM0MzYVl2ZUwu/anBn", quantity: 1),

  ];
  
  static List<Product> Vegetables = [
  Product(
    id: 1,
    name: 'Carrot',
    category: 'Vegetables',
    price: 30.0, 
    description: 'Fresh and crunchy carrots rich in vitamins.',
    image: 'https://imgs.search.brave.com/3F1BZWwjx9473_ALub2SWqea5wfg6OThyaW6zqw5JyA/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5nZXR0eWltYWdl/cy5jb20vaWQvOTA5/MjE2NzI2L3Bob3Rv/L2NhcnJvdC5qcGc_/cz02MTJ4NjEyJnc9/MCZrPTIwJmM9RUFi/ZTJLR0JIOU9Sd0JU/dE9Faml3d2hVRk80/MU1RMmxKbVRnLXlJ/azZndz0',
    quantity: 1,
  ),
  Product(
    id: 2,
    name: 'Broccoli',
    category: 'Vegetables',
    price: 40.0,
    description: 'Green and nutritious broccoli with a high vitamin C content.',
    image: 'https://imgs.search.brave.com/l-T_UZ55GzMEmlKNLB2ES2R3sPxY7dAipKfO-Mkr3fc/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5pc3RvY2twaG90/by5jb20vaWQvMTQ3/MDYwNjIxL3Bob3Rv/L2Jyb2Njb2xpLmpw/Zz9zPTYxMng2MTIm/dz0wJms9MjAmYz1J/MWNDeEx4Y2kyM25y/U05aYjdvNmdzcVVZ/QjkxMXo2SVpsTGRF/T2s0STlNPQ',
    quantity: 1,
  ),
  Product(
    id: 3,
    name: 'Tomato',
    category: 'Vegetables',
    price: 25.0,
    description: 'Juicy tomatoes perfect for salads and cooking.',
    image: 'https://imgs.search.brave.com/l1uhgFLvv-ygZtfCMKqkXf0JA7kCgvKwKV2D2lYwjiU/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly91cGxv/YWQud2lraW1lZGlh/Lm9yZy93aWtpcGVk/aWEvY29tbW9ucy90/aHVtYi84Lzg5L1Rv/bWF0b19qZS5qcGcv/NTEycHgtVG9tYXRv/X2plLmpwZw',
    quantity: 1,
  ),
  Product(
    id: 4,
    name: 'Spinach',
    category: 'Vegetables',
    price: 50.0,
    description: 'Fresh spinach leaves rich in iron and vitamins.',
    image: 'https://imgs.search.brave.com/py1df258pGzMhhgtRKczhDHeui7Ha0HuuQ3aY0NyBGk/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5nZXR0eWltYWdl/cy5jb20vaWQvMTY5/OTgzNzkxL3Bob3Rv/L3NwaW5hY2guanBn/P3M9NjEyeDYxMiZ3/PTAmaz0yMCZjPTFM/OXFKTDNCVFl1ck85/N0h5RXhmRVNrS3lG/UkV6UjM1RVJlSEhs/aDlpYms9',
    quantity: 1,
  ),
  Product(
    id: 5,
    name: 'Cucumber',
    category: 'Vegetables',
    price: 20.0,
    description: 'Crisp and refreshing cucumbers, great for salads.',
    image: 'https://imgs.search.brave.com/CCwd3ggQUAIXxSgyRYhbhDEcvg8TyUOuXljMcMgYkZ4/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5pc3RvY2twaG90/by5jb20vaWQvMTUz/NTU2MzM2L3Bob3Rv/L2N1Y3VtYmVyLXNs/aWNlLmpwZz9zPTYx/Mng2MTImdz0wJms9/MjAmYz1NV294cmM0/bk9uU2FkU1hRclZD/TEd5N29SNmt2eWVO/TDFOamI1bGg4Zl9J/PQ',
    quantity: 1,
  ),
  Product(
    id: 6,
    name: 'Bell Pepper',
    category: 'Vegetables',
    price: 35.0,
    description: 'Sweet and crunchy bell peppers in various colors.',
    image: 'https://imgs.search.brave.com/-SiHQIvnrV4Rxkt2Ix679CdCwBceMImwovOhyCBIw9k/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5nZXR0eWltYWdl/cy5jb20vaWQvMTcx/MjgxMzY0L3Bob3Rv/L2JlbGwtcGVwcGVy/cy5qcGc_cz02MTJ4/NjEyJnc9MCZrPTIw/JmM9UHBycDBjQzh3/ODZ2VHRUXzhDS1pv/bHliU25HLWcxOGFY/S2U4OHUyVi01dz0',
    quantity: 1,
  ),
  Product(
    id: 7,
    name: 'Potato',
    category: 'Vegetables',
    price: 25.0,
    description: 'Versatile and hearty potatoes for various dishes.',
    image: 'https://imgs.search.brave.com/PSjRGSd8lGymy8L-NE0eLb8iDEfvgpidKeIxsOUpbBo/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly90My5m/dGNkbi5uZXQvanBn/LzAwLzg1Lzc5Lzky/LzM2MF9GXzg1Nzk5/Mjc4XzBCQkdWOU9B/ZFFEVExuS3dBUEJD/Y2cxSjdRdGlpZUpZ/LmpwZw',
    quantity: 1,
  ),
  Product(
    id: 8,
    name: 'Onion',
    category: 'Vegetables',
    price: 30.0,
    description: 'Essential cooking ingredient with a strong flavor.',
    image: 'https://imgs.search.brave.com/RB8DTE3u7C1EghTdDA_LH_qDv8t5o-z_wnh3miLvFSo/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9pbWcu/ZnJlZXBpay5jb20v/ZnJlZS1waG90by9y/ZWQtb25pb25fMTQ0/NjI3LTE1NDE2Lmpw/Zz9zaXplPTYyNiZl/eHQ9anBn',
    quantity: 1,
  ),
  Product(
    id: 9,
    name: 'Garlic',
    category: 'Vegetables',
    price: 40.0,
    description: 'Aromatic garlic cloves perfect for flavoring dishes.',
    image: 'https://imgs.search.brave.com/Lw3PZUWZO9HQXZs6mt5Q9YcgA1ueW4_XvtsbjYzaEOU/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5pc3RvY2twaG90/by5jb20vaWQvNDk5/MTQ3ODY0L3Bob3Rv/L2dhcmxpYy5qcGc_/cz02MTJ4NjEyJnc9/MCZrPTIwJmM9LTli/NDgzVjZVUDJVcmxq/RVlaRGNFQkV3emtQ/cWIzdTVNSUozLU1h/b2Z1Yz0',
    quantity: 1,
  ),
  Product(
    id: 10,
    name: 'Sweet Potato',
    category: 'Vegetables',
    price: 45.0,
    description: 'Nutritious and sweet, ideal for roasting or baking.',
    image: 'https://imgs.search.brave.com/p7U6DqKhDg_yV-8en-cVtfow1drcrr8Hm6CNEYexxEI/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly90My5m/dGNkbi5uZXQvanBn/LzAyLzI0LzkxLzk0/LzM2MF9GXzIyNDkx/OTQ1OV9HMDhLWENY/NVo2N0N2RlhUd1J4/ell6azl2WVZ5Qkcx/SS5qcGc',
    quantity: 1,
  ),
  Product(
    id: 11,
    name: 'Cauliflower',
    category: 'Vegetables',
    price: 55.0,
    description: 'Versatile cauliflower, great for steaming or stir-frying.',
    image: 'https://imgs.search.brave.com/PTtTKQnJ7bAJISEdd2_zWA6keeR3OzpZOF1b2-lEp-4/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5nZXR0eWltYWdl/cy5jb20vaWQvODU2/MzY5MjEvcGhvdG8v/Y2F1bGlmbG93ZXIu/anBnP3M9NjEyeDYx/MiZ3PTAmaz0yMCZj/PW5YUG5RUXdFWFdK/c25vZnZ0MG9TeWh6/aldMOHpNbzBldFV6/M281dlo3cFU9',
    quantity: 1,
  ),
  Product(
    id: 12,
    name: 'Green Beans',
    category: 'Vegetables',
    price: 35.0,
    description: 'Crisp and fresh green beans, perfect for a side dish.',
    image: 'https://imgs.search.brave.com/O5LIftgwZS7wRf9qX6uKKz83Yrvfdq1Uih9phK6Ew4I/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly93d3cu/dHdvcGVhc2FuZHRo/ZWlycG9kLmNvbS93/cC1jb250ZW50L3Vw/bG9hZHMvMjAxOS8w/OC9Ud29QZWFzX1NM/Q18yNTA4LTY1MHg5/NzUuanBn',
    quantity: 1,
  ),
  Product(
    id: 13,
    name: 'Zucchini',
    category: 'Vegetables',
    price: 30.0,
    description: 'Tender zucchinis ideal for grilling or sautéing.',
    image: 'https://imgs.search.brave.com/GhyJ4ZR5Q_MgYAHqeOZn3-sYheyTvrVbFGswUpn_hwo/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly90NC5m/dGNkbi5uZXQvanBn/LzAwLzY5Lzg4LzY3/LzM2MF9GXzY5ODg2/NzEzX2d1RWFMaE1T/aVM5N1VDUnlBQjN5/S2ZqYVY4VDMxQVRZ/LmpwZw',
    quantity: 1,
  ),
  Product(
    id: 14,
    name: 'Eggplant',
    category: 'Vegetables',
    price: 50.0,
    description: 'Rich and flavorful eggplants for a variety of dishes.',
    image: 'https://imgs.search.brave.com/EnqZkY5NS4m80Z0eROlVuAFLZvRJyWzI1uEwkBK_ko8/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly90My5m/dGNkbi5uZXQvanBn/LzAwLzc4LzM3Lzc0/LzM2MF9GXzc4Mzc3/NDU5X1laMmd4ZTQ2/UEptZ3RwWGplSEM1/bDZxUU9MdElmcGUz/LmpwZw',
    quantity: 1,
  ),
  Product(
    id: 15,
    name: 'Beetroot',
    category: 'Vegetables',
    price: 40.0,
    description: 'Sweet and earthy beetroot for salads and juices.',
    image: 'https://imgs.search.brave.com/QG4Ok3EJ8btGjADi3AgNNzQG1fsJX6e-T3gL8lP0Ry4/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5pc3RvY2twaG90/by5jb20vaWQvMTYy/NjgyOTYxL3Bob3Rv/L2JlZXRyb290Lmpw/Zz9zPTYxMng2MTIm/dz0wJms9MjAmYz1B/ekhtSjZmUGE0NEJO/N3lfcmppOW56aUlY/TXVPclBlVTUwMktw/c1B2NktzPQ',
    quantity: 1,
  ),
  Product(
    id: 16,
    name: 'Sweet Corn',
    category: 'Vegetables',
    price: 30.0,
    description: 'Sweet and juicy corn on the cob, great for grilling.',
    image: 'https://imgs.search.brave.com/HuQHwNh3Urz5nAuNNeMauHl__bsHQHtV673m1pgf_Z4/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5nZXR0eWltYWdl/cy5jb20vaWQvMTUz/NDgyNTcyL3Bob3Rv/L3N3ZWV0LWNvcm4u/anBnP3M9NjEyeDYx/MiZ3PTAmaz0yMCZj/PUlvd09fNHA4VG5w/eXVITUhPTG1QWnNn/d3lLMVdzenAyd3kx/aDVvSWZ6bG89',
    quantity: 1,
  ),
  Product(
    id: 17,
    name: 'Radish',
    category: 'Vegetables',
    price: 25.0,
    description: 'Crunchy radishes with a spicy kick.',
    image: 'https://imgs.search.brave.com/Bnj33ej_qtTz9Sn8zB1Ox-QlLdYhz0z8f_Gk4iiUVBM/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5nZXR0eWltYWdl/cy5jb20vaWQvMTQz/NDUwNTA4L3Bob3Rv/L3doaXRlLXJhZGlz/aC5qcGc_cz02MTJ4/NjEyJnc9MCZrPTIw/JmM9QW80Z2ItQm1h/WlZhT2lKVDdqR0lV/SEdOWFRhQVNncVZU/ZFByTjVUYm0xOD0',
    quantity: 1,
  ),
  Product(
    id: 18,
    name: 'Kale',
    category: 'Vegetables',
    price: 40.0,
    description: 'Nutrient-dense kale leaves, great for salads and smoothies.',
    image: 'https://imgs.search.brave.com/qz7Vm0fMgB3E4dvBN2CDo_1N7hiGUFeaAF4bSPvn_Ls/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9pMC53/cC5jb20vaW1hZ2Vz/LXByb2QuaGVhbHRo/bGluZS5jb20vaGxj/bXNyZXNvdXJjZS9p/bWFnZXMvQU5faW1h/Z2VzL2JlbmVmaXRz/LW9mLWthbGUtMTI5/Nng3MjgtZmVhdHVy/ZS5qcGc_dz0xMTU1/Jmg9MTUyOA',
    quantity: 1,
  ),
  Product(
    id: 19,
    name: 'Brussels Sprouts',
    category: 'Vegetables',
    price: 60.0,
    description: 'Nutritious Brussels sprouts, ideal for roasting.',
    image: 'https://imgs.search.brave.com/2AKtaZysWZZ7OxzpHKrxcZF4AFW88xDnUzFNxACvnFk/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5pc3RvY2twaG90/by5jb20vaWQvMTcw/MDY5NTk2L3Bob3Rv/L2JydXNzZWxzLXNw/cm91dHMuanBnP3M9/NjEyeDYxMiZ3PTAm/az0yMCZjPTlxMzkz/LThkSHlqaEh2V3Vy/Tlp5RWMzQ29xMDBq/cmhqQVUzRG1kcTZC/WUU9',
    quantity: 1,
  ),
  Product(
    id: 20,
    name: 'Pumpkin',
    category: 'Vegetables',
    price: 70.0,
    description: 'Sweet and versatile pumpkin, perfect for soups and pies.',
    image: 'https://imgs.search.brave.com/EWw9hYzw5sWJ5ClWerdqQ4YnG8Hb4hlgU5DUKm-zB6s/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly90My5m/dGNkbi5uZXQvanBn/LzA0Lzk2LzM2LzY0/LzM2MF9GXzQ5NjM2/NjQ1Ml8wVnZzdE45/ZXBxbGRIVHdYbUE3/WWFiRHJ3VUdid2lT/VC5qcGc',
    quantity: 1,
  ),
];

  static List<Product> cleaners = [
  Product(
    id: 1,
    name: 'All-Purpose Cleaner',
    category: 'Cleaners',
    price: 200.00,
    description: 'Versatile cleaner suitable for multiple surfaces.',
    image: 'https://imgs.search.brave.com/kJXAvsLViYV74dsp02pldqtuPzRblx9mGlPYsvpaNvI/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9oaXBz/LmhlYXJzdGFwcHMu/Y29tL3ZhZGVyLXBy/b2QuczMuYW1hem9u/YXdzLmNvbS8xNjU1/NTAzMDc4LTUxOTJ5/MzZ2WHlMLl9TTDUw/MF8uanBnP2Nyb3A9/MXh3OjEuMDB4aDtj/ZW50ZXIsdG9wJnJl/c2l6ZT05ODA6Kg',
    quantity: 1,
  ),
  Product(
    id: 2,
    name: 'Glass Cleaner',
    category: 'Cleaners',
    price: 150.0,
    description: 'Leaves glass surfaces streak-free and sparkling.',
    image: 'https://imgs.search.brave.com/H95ewogiWcJxnUXm60NrCTwCfd84YYSmaQew1jyuGNU/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly93d3cu/cHJvd2F4LmNvbS9j/ZG4vc2hvcC9wcm9k/dWN0cy9BR0MtMTgt/QWVyb3NvbC1HbGFz/cy1DbGVhbmVyXzUz/M3guanBnP3Y9MTY0/OTgyODk5OQ',
    quantity: 1,
  ),
  Product(
    id: 3,
    name: 'Disinfectant Spray',
    category: 'Cleaners',
    price: 100.0,
    description: 'Kills germs and bacteria on various surfaces.',
    image: 'https://imgs.search.brave.com/oGNp2ZvTNs3l7g830Pj7pQfiTL-Cf3WX71W_HG3tXyk/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS1jbGRucnkucy1u/YmNuZXdzLmNvbS9p/bWFnZS91cGxvYWQv/dF9maXQtMzIwdyxm/X2F1dG8scV9hdXRv/OmJlc3QvbmV3c2Nt/cy8yMDIzXzE3LzM1/NzM5MzYvZ3Vlc3Qt/ZTVlMzM0YmMtNGU0/NS00OGFlLWI1Yjgt/ZjM3MjczYzQxODUy/LTYzM2MzYTQ2OGEy/MDIuanBn',
    quantity: 1,
  ),
  Product(
    id: 4,
    name: 'Floor Cleaner',
    category: 'Cleaners',
    price: 200.0,
    description: 'Specially formulated for cleaning all types of flooring.',
    image: 'https://imgs.search.brave.com/NdDlQ3YM1cOdMbKfGOppOSwTxX2Aet4maLN17LX-DrQ/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly93d3cu/ZmFtaWx5aGFuZHlt/YW4uY29tL3dwLWNv/bnRlbnQvdXBsb2Fk/cy8yMDIxLzA0LzUx/SHFZbDFySFNMLl9B/Q19TWDY3OV8uanBn/P2ZpdD02OTYsNjk2',
    quantity: 1,
  ),
  Product(
    id: 5,
    name: 'Bathroom Cleaner',
    category: 'Cleaners',
    price: 180.0,
    description: 'Removes tough stains and grime from bathroom surfaces.',
    image: 'https://imgs.search.brave.com/49q8PEN4zTqc6YEPYmpADCSi3bZ7TVFVmtxk70oA7dM/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL0kv/NzFyZzFZTjg4cUwu/anBn',
    quantity: 1,
  ),
  Product(
    id: 6,
    name: 'Kitchen Degreaser',
    category: 'Cleaners',
    price: 220.0,
    description: 'Cuts through grease and grime in the kitchen.',
    image: 'https://imgs.search.brave.com/tgI5EAALDqTf03zEMRjmDZ22UyvHqJc3CKxnjndrFJI/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL0kv/NTFEbzBRUXFKUEwu/anBn',
    quantity: 1,
  ),
  
  Product(
    id: 7,
    name: 'Carpet Cleaner',
    category: 'Cleaners',
    price: 9000.0,
    description: 'Deep cleans and refreshes carpets.',
    image: 'https://imgs.search.brave.com/WuVZLSRN1tpbMqlWoB3EsU2-_4DC5VWPzZ3wDMUdIiE/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5nZXR0eWltYWdl/cy5jb20vaWQvMTgy/NzM4NTMzL3Bob3Rv/L2NhcnBldC1jbGVh/bmVyLXJlc2lkZW50/aWFsLmpwZz9zPTYx/Mng2MTImdz0wJms9/MjAmYz1BRHptY1pp/aFI3LWJnZV82Uk12/RG1vbEJmSlZGdWRX/djI5RWptQzhxUEJN/PQ',
    quantity: 1,
  ),
  Product(
    id: 9,
    name: 'Wood Polish',
    category: 'Cleaners',
    price: 170.0,
    description: 'Enhances the shine and protects wooden surfaces.',
    image: 'https://imgs.search.brave.com/XIqDDOzaoxmSLy2VpEqmjMs12zmRNE7e3ib9pJtMHKQ/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL0kv/NzFOQmZIUytvcFMu/anBn',
    quantity: 1,
  ),
  Product(
    id: 12,
    name: 'Leather Cleaner',
    category: 'Cleaners',
    price: 240.0,
    description: 'Specially designed for cleaning and conditioning leather.',
    image: 'https://imgs.search.brave.com/ZjMDowlez9M8qAcVf-PznHp_ubGBJuI1G2pVoSFpJQM/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93d3cu/bGVhdGhlcmhvbmV5/LmNvbS9jZG4vc2hv/cC9maWxlcy9NYWlu/OG96XzE2MDB4Lmpw/Zz92PTE3MTUxMzE1/MjQ',
    quantity: 1,
  ),
  Product(
    id: 13,
    name: 'Toilet Bowl Cleaner',
    category: 'Cleaners',
    price: 120.0,
    description: 'Cleans and disinfects toilet bowls with ease.',
    image: 'https://imgs.search.brave.com/x951gckqB8BLLt1TqFcoIKSBHZjDNUQoLNEkY3prSbw/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9sZW1p/c2hpbmUuY29tL2Nk/bi9zaG9wL2ZpbGVz/L1RvaWxldC1Cb3ds/LUNsZWFuZXItMjQt/T3ouanBnP3Y9MTcw/NTY3NjE0OCZ3aWR0/aD0xMDAw',
    quantity: 1,
  ),

];
}